kind: Service
apiVersion: v1
metadata:
  name: intertodo
  namespace: dev
spec:
  selector:
    app: intertodo
    tier: app
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
  type: ClusterIP